### PR TITLE
CDF loading between starttime and endtime to save computing time.

### PR DESCRIPTION
**Pull request by dupuisIRT**
Loading of the CDF file is done between starttime and endtime to save computing time.
See #764

### CODE REVIEW

**Comment by dstansby** [comment]
Had a look over this - I'm not sure how it would interact with the converting to `.hdf` files option, as currently the model is the whole of a .cdf file is read in and saved to a .hdf file.

I've also found a few areas that are making cdf reading very slow, which I'm currently fixing, which I think should speed up reading in large CDF files by a factor of ~100 (!!!). I'll let you know when I've added those changes, and maybe reading in files will be fast enough that this optimisation isn't needed?

**Comment by dupuisIRT** [comment]
Sure, if reading is speed up by a factor of x100 this part seems useless.

**Comment by dupuisIRT** [comment]
Hi @dstansby, did you make any progress with the optimisation for CDF?

**Comment by dstansby** [comment]
Oh yes, sorry I forgot to reply. Yes, new versions of heliopy (0.10.0) and cdflib should speed things up a lot. If you update you should see a big performance improvement. I now wonder if it's worth removing the option to save to `.hdf` files (I need to do a check on the difference between loading a cdf and a hdf file). If there's not much difference, then I think it's worth going ahead with this change - I will let you know in the next couple of days.

**Comment by dupuisIRT** [comment]
@dstansby wow, it is much faster, great work! Thanks a lot.

**Pull request closed without merging**
