### PR TITLE
Added sunspot data importing with different timeframes

### PR DESCRIPTION
**Pull request by abotiamnot**
Added multiple functions to import data from different time-frames. 

To use, 

```
import heliopy.data.sunspot as sunspot
sunspot.daily()
sunspot.monthly()
sunspot.yearly()
```

Will add the test files ASAP!

### CODE REVIEW

**Comment by abotiamnot** [comment]
What exactly does codecov do, by the way? By the way, I've added the daily(), monthly() and yearly() into the module! Please take a look, and thanks a lot!

**Comment by abotiamnot** [comment]
@dstansby I can't seem to figure out how the test file works in conjunction with another file. Can you write one? Or give a short explanation how it works? Thanks!

**Comment by dstansby** [comment]
This looks pretty good now. Would it be possible to squash the commits into one? If you do
```
git rebase -i heliopython/master
```
that should give you a list of all the commits, and you can change all but the first 'pick' to 'squash', which will put everything into one comment. Then you can force push the branch using `git push -f`.

**Comment by abotiamnot** [comment]
@dstansby I ran the tests again, worked successfully!

**Comment by dstansby** [comment]
Nice, thanks! I'm going to go ahead an merge this. Congratulations on being the first person that isn't me to add some new functionality to HelioPy!

**Comment by abotiamnot** [comment]
Thanks a lot! :D

**Pull request merged**
