### PR TITLE
Cassini CAPS ELS data downloader

### PR DESCRIPTION
**Pull request by RichardHaythorn**
-Adds functionality to download Cassini Plasma Spectrometer (CAPS) Electron Spectrometer (ELS) data, sets up structures for adding CAPS IMS and CAPS IBS in future (also possibly Juno JADE data) 
-Adds "load_local_hdf_file" in util, allows more freedom with HDF5 creation

### CODE REVIEW

**Comment by dstansby** [comment]
Thanks for this, looks 👍 . Could you add a quick test in `heliopy/data/tests/test_cassini.py`? Hopefully it should be easy enough to copy/paste/adapt an existing one - let me know if you have any questions.

**Comment by dstansby** [comment]
👋 Thanks for opening this PR. As of today, I've put heliopy into hibernation, which means I'm no longer reviewing or implementing new feature requests. I'll leave this issue open in case this changes in the future, but thought I should let anyone subscribed to this PR.

**Comment by dstansby** [comment]
Thanks for the PR 👍. I'm currently trying to overhaul heliopy a bit to access generic data repositories, instead of having specific downloading/loading code (where possible). As such, I'm going to close this PR. If you're still interested in adding this data though, it would be great to open an issue at https://github.com/heliopython/heliopy/issues and I can look into what the best approach will be.

**Comment by RichardHaythorn** [comment]
With all the pandemic stuff this sideproject got pushed under the rug! I was never too happy with how i implemented this but i would be interested in a more generic downloader. The issue with CAPS data (similarly Juno JADE which i've looked at) is the need to download the format file as well as the data, to get it out of its flat binary format. The other thing is the multidimensionality of the data. I'll have a think about this as well.

**Pull request closed without merging**
