### PR TITLE
Improve FTP code

### PR DESCRIPTION
**Pull request by dstansby**

### CODE REVIEW

**Comment by dstansby** [comment]
Hmm, all the errors seem to be where a method uses `ftp.nlst`: https://travis-ci.org/heliopython/heliopy/jobs/359368236

**Comment by abotiamnot** [comment]
It says connection timed out in some, is it because Travis failed to download those files?

**Comment by dstansby** [comment]
It seems to be not connecting to servers properly. I'm trying to add some logging/debugging statements at the moment.

**Comment by abotiamnot** [comment]
Did a really bad logging using print statements. It seems that the [build failed](https://travis-ci.org/abotiamnot/heliopy/jobs/359942926) at ftp.nlst(server_dir) in util.

**Comment by dstansby** [comment]
Turns out this is a known issue: https://github.com/travis-ci/travis-ci/issues/9391

Moving the build to non-sudo architecture should fix it, which I'm doing in #401

**Pull request merged**
