### PR TITLE
Added JUNO Kernel

### PR DESCRIPTION
**Pull request by abotiamnot**
Added JUNO Reconstructed and JUNO Predicted SPK kernel files.

### CODE REVIEW

**Comment by dstansby** [comment]
Could these be split up into two (maybe `Juno_pred` and `Juno_recon`?)

**Comment by abotiamnot** [comment]
@dstansby I've got a question, why is there a Helios 1 kernel inside the Helios 2 dict entry? I'm not sure so asking this!

**Comment by dstansby** [comment]
I'm not sure actually, that should be fixed...

**Comment by abotiamnot** [comment]
I'm guessing there must be a reason it was added. Should we let it stay for the time being?

**Comment by dstansby** [comment]
It should really live in the Helios 1 entry, but that can be fixed another time.

**Pull request merged**
