### PR TITLE
Stereo SEP instruments to heliopy

### PR DESCRIPTION
**Pull request by tlml**
Hi David,

At long last... I emailed you probably about a year ago, and chatted at NAM in the Summer about STEREO SEP instruments. Other things got on the way (as they always do), but now I have finally got there... The code is freshly-rebased, and the added stuff works, I needed to change a couple of things in cdasrest.py and util.py in heliopy/data (plus of course adding a bunch of units to helper.py.

Included are also a couple of ACE particle instruments that I thought were on a different branch...

All the stuff works, I couldn't run the tests though as my setup complained about size mismatch of internals between numpy and pandas...

Cheers,

Timo (Laitinen, UCLan)

### CODE REVIEW

**Comment by dstansby** [comment]
Hi Timo, thanks a lot for this,

Since this is quite a big change, it will take me a while to look over everything. It might be a good idea to split this into smaller PRs if that's possible? At a glance, the ACE stuff could easily go by itself, and I could review and merge that pretty easily. If you want I would be happy to do that myself, and try and split some other stuff out too - let me know. Thanks again for the PR!

**Comment by tlml** [comment]
Hi David,

No problem! The ACE stuff was actually originally on a separate branch, but
I seem to have merged it at some point (I started this quite a while ago,
and then continued a much later...). I vaguely remember that the ACE stuff
was very straightforward, mainly the additions to the helper.py cdf_dict().
Happy for you to split! (this actually is my first-ever pull request so I
wouldn't know where to go for splitting purposes...).

Cheers,

Timo

**Comment by dstansby** [comment]
The easiest way is probably to start with a new branch that doesn't have any changes, add the changes to the ACE file(s), and then create a new pull request from that branch. Does that help?

**Comment by dstansby** [comment]
Hey @tlml, since the ACE instruments were pretty easy to add I did them here: #882. I'll try and have a look at the STEREO stuff too at some point.

**Comment by tlml** [comment]
Hi @dstansby , Great! Sorry I haven't had time to look into it at all, very busy and chaotic times...

**Comment by dstansby** [comment]
👋 Thanks for opening this PR. As of today, I've put heliopy into hibernation, which means I'm no longer reviewing or implementing new feature requests. I'll leave this issue open in case this changes in the future, but thought I should let anyone subscribed to this PR.

**Comment by dstansby** [comment]
Hi Timo, I am planning on writing a generic data access method for data from CDAWEB/SPDF, so I'm going to close this. Thanks a lot for opening it though, and apologies that it didn't go anywhere in the end.

**Pull request closed without merging**
