### PR TITLE
STEREO files listed dynamically

### LINKED ISSUE #657: Automatically detect STEREO-A kernels to be downloaded
Currently the STEREO-A spice kernels are hardcoded, but their names keep changing. It should be possible to list the files in the directory instead to get the right filenames each time.

### PR DESCRIPTION
**Pull request by ritzvik**
Fixes #657

### CODE REVIEW

**Comment by ritzvik** [comment]
One small suggestion from my side is that the repo can make use of `black`. See https://black.readthedocs.io/en/stable/the_black_code_style.html

`pip install black` and then `black heliopy/data/spice.py` and one can see the difference.

I am extremely sorry if it seems unnecessary but I felt that this can make code adhere to a specific style and can ease future contributions as the contributor can edit the code in his own way and just apply `black` on it after the changes.

The style checking part can be done in CircleCI for each PR.

**Comment by ritzvik** [comment]
@dstansby would you be reviewing the PR, if possible?

**Comment by ritzvik** [comment]
@dstansby Made the recommended changes as well as sorted the imports using `isort`. 

I think the kernels would be downloaded ever time even now, as all the global variables would be itialized

**Comment by ritzvik** [comment]
Sorry for creating a mess. I would squash the commits after things are finalized.

**Comment by ritzvik** [comment]
@dstansby The coverage is decreasing. Could you guide me with the tests?

**Comment by dstansby** [comment]
Coverage looks good to me, it's just because the errors you provided aren't being run in the tests. This all looks good to me, thanks a lot for your first PR to HelioPy!

**Comment by ritzvik** [comment]
> Coverage looks good to me, it's just because the errors you provided aren't being run in the tests. This all looks good to me, thanks a lot for your first PR to HelioPy!

Welcome 😃 . Any more issues I can solve?

**Pull request merged**
